import type { Metadata } from "next";
import { Space_Grotesk, Rethink_Sans } from "next/font/google";
import "./globals.css";
import ClickSpark from "@/components/ui/ClickSpark";
import Navbar from "@/components/Navbar";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const rethinkSans = Rethink_Sans({
  variable: "--font-rethink-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${rethinkSans.variable} antialiased flex flex-col items-center w-screen min-h-screen font-rethink-sans text-black-text`}
      >
        <ClickSpark
          sparkColor='#00000'
          sparkSize={10}
          sparkRadius={15}
          sparkCount={8}
          duration={400}
        >
          <Navbar/>
          {children}
        </ClickSpark>
      </body>
    </html>
  );
}
